import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from fastapi import FastAPI, BackgroundTasks, HTTPException
from contextlib import asynccontextmanager
from pydantic import BaseModel
import uvicorn
import logging
from src.main import AgenticSystem
from src.config import Config

logger = logging.getLogger("query_bot")

# Global reference to our system
system = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    global system
    logger.info("Initializing Agentic System (Query Bot)...")
    system = AgenticSystem()
    yield
    logger.info("Shutting down Query Bot...")

app = FastAPI(title="Probability Cup Query Bot", lifespan=lifespan)

class QueryRequest(BaseModel):
    question: str
    model: str = None  # Optional: "gemini-3.5-flash" or "gemini-3.5-flash-lite"
    match_id: str = None # Optional precise match identifier

@app.get("/api/status")
async def get_status():
    """System health and queue status."""
    return {
        "status": "online",
        "event_id": system.event_id,
        "upcoming_matches": system.db.get_upcoming_matches(within_minutes=72*60)
    }

@app.get("/api/matches")
async def get_matches():
    """List all matches in DB."""
    return system.db.get_all_matches()

@app.get("/api/dashboard")
async def get_dashboard():
    """Calibration and performance dashboard."""
    return system.calibrator.get_dashboard_data()

@app.post("/api/ask")
async def ask_question(req: QueryRequest):
    """
    Ask a question.
    Will do a quick refresh and re-sim if it's about an upcoming match.
    """
    target_match = None
    
    if req.match_id:
        target_match = system.db.get_match(req.match_id)
        if not target_match:
             return {"answer": f"I couldn't find a match with ID {req.match_id} in the database."}
    else:
        # Fallback to simple keyword matching if no explicit match_id is provided
        q = req.question.lower()
        matches = system.db.get_upcoming_matches(within_minutes=72*60)
        for match in matches:
            if match.get("home_team_name", "").lower() in q or match.get("away_team_name", "").lower() in q:
                target_match = match
                break
            
    if target_match:
        match_id = target_match.get("id")
        logger.info(f"Query targets match {match_id}. Doing quick refresh and resim.")
        
        # 1. Quick Refresh
        system.collector.quick_refresh(match_id)
        
        # 2. Resimulate
        updated_match = system.db.get_match(match_id)
        home_team_stats = system.db.get_team(updated_match.get("home_team_id"))
        away_team_stats = system.db.get_team(updated_match.get("away_team_id"))
        classified = system.db.get_markets(match_id)
        sim_results = system.engine.simulate_match(updated_match, home_team_stats, away_team_stats, classified)
        system.db.save_simulations(match_id, sim_results)
        
        # 3. Generate Local Predictions (Don't submit)
        news = system.db.get_news(match_id)
        structured = system.db.get_structured_news(match_id)
        bot1_preds = system.predictor.predict(1, sim_results, news, structured, classified, updated_match)
        bot2_preds = system.predictor.predict(2, sim_results, news, structured, classified, updated_match)
        
        system.db.save_predictions_local_cache(match_id, bot1_preds, bot2_preds)
        
        # 4. Use AI to answer
        # The prompt that the Query Bot will use to format its response to the user
        query_system_prompt = """You are the Probability Cup Query Bot.
Your sole job is to provide the user with ONE final, definitive probability (1-99) for them to use, along with a concise explanation.

You will be provided with:
1. The user's specific question.
2. The final prediction integers generated by Bot 1 (Calibrated Baseline) and Bot 2 (Edge Hunter).
3. The Monte Carlo simulation results and news context.

Rules for your response:
1. Synthesize the findings of Bot 1 and Bot 2.
2. Output the single best recommended probability (integer 1-99) that maximizes Relative Brier Point (RBP).
3. Output a clear, concise, data-driven explanation for this number (referencing the simulations and edge analysis).
4. DO NOT output anything else. No pleasantries, no generic commentary. Just the probability and the explanation."""

        if system.ai_client:
            # Here we pass the highly detailed prompt along with all the context
            selected_model = req.model if req.model else Config.QUERY_BOT_MODEL
            answer = system.ai_client.answer_query(
                system_prompt=query_system_prompt,
                question=req.question, 
                bot1_preds=bot1_preds, 
                bot2_preds=bot2_preds, 
                match_data=updated_match,
                model=selected_model
            )
        else:
            answer = f"I've refreshed the data and run new simulations for {updated_match.get('name')}. Bot 1 recommends probability {bot1_preds[0]['probability']} for the main market. Bot 2 recommends {bot2_preds[0]['probability']} based on edge analysis. (Note: Integrate google-genai client to see the full analytical breakdown)."
            
        return {"answer": answer, "match_id": match_id}
        
    return {"answer": "I couldn't identify a specific upcoming match in your query. I only know about matches in the database."}

if __name__ == "__main__":
    uvicorn.run("src.query_bot:app", host="0.0.0.0", port=8000, reload=True)
